#!/usr/bin/env bash
set -euo pipefail

if ! test -f pyproject.toml; then
  echo "Missing pyproject.toml"
  exit 1;
fi

export APP_NAME="quakeservices"
export CODE_DIR="/opt/$APP_NAME"
export CI=${CI:-}

export MASTER_NAME="master"
export MASTER_DIR="master"
export MASTER_PORT="27900/udp"
export MASTER_HEALTHCHECK="8080/tcp"

export AWS_DEFAULT_REGION="us-west-2"

#
# Depenency versions
#
export PIP_VERSION="23.3.1"
export DOCKER_VERSION="24.0.6"
export NODE_VERSION="18.18.2"

CDK_VERSION=$(awk '/^aws-cdk-lib = / {gsub(/"/, "", $3); gsub(/\^/, "", $3); print $3}' pyproject.toml)
export CDK_VERSION
POETRY_VERSION=$(awk '/^poetry = / {gsub(/"/, "", $3); gsub(/\^/, "", $3); print $3}' pyproject.toml)
export POETRY_VERSION

#
# Docker / GHCR / ECS Tags
#

export BASE_GHCR_TAG="ghcr.io/${APP_NAME}/base"
export MASTER_GHCR_TAG="ghcr.io/${APP_NAME}/master"
export CDK_BASE_GHCR_TAG="ghcr.io/${APP_NAME}/cdk-base"
export CDK_GHCR_TAG="ghcr.io/${APP_NAME}/cdk"
export DOCS_GHCR_TAG="ghcr.io/${APP_NAME}/docs"
export TEST_GHCR_TAG="ghcr.io/${APP_NAME}/test"

export HADOLINT_TAG="ghcr.io/hadolint/hadolint:latest"
export SHELLCHECK_TAG="docker.io/koalaman/shellcheck-alpine:latest"

CONTAINER_AWS_OPTIONS=(
  --env AWS_ACCESS_KEY_ID
  --env AWS_SECRET_ACCESS_KEY
  --env AWS_ACCOUNT
  --env AWS_SECURITY_TOKEN
  --env AWS_DEFAULT_REGION
)
CONTAINER_RUN_OPTIONS=(
  --interactive
  --rm
  --tty
  --workdir "${PWD}"
)

CONTAINER_BUILD_OPTIONS=(
  --build-arg "CODE_DIR=$CODE_DIR"
  --build-arg "PIP_VERSION=$PIP_VERSION"
  --build-arg "POETRY_VERSION=$POETRY_VERSION"
)

#
# Docker / Podman support
#
export DOCKER_BUILDKIT=1

if which podman > /dev/null 2>&1; then
  export CONTAINER_COMMAND="podman"
  export COMPOSE_COMMAND="podman-compose"
  CONTAINER_SOCKET=$(podman info | awk -F': ' '/podman.sock/ {print $2}')
  if [[ ! "$CONTAINER_SOCKET" ]]; then
    echo "Missing podman user socket"
    echo "See https://github.com/containers/podman/blob/main/docs/tutorials/socket_activation.md for setup."
    exit 1
  fi
  export MOUNT_SOCKET=" --mount=type=bind,source=${CONTAINER_SOCKET},target=${CONTAINER_SOCKET},relabel=private"
  export MOUNT_PWD=" --mount=type=bind,source=${PWD},target=${PWD},relabel=private"
  export MOUNT_AWS=" --mount=type=bind,source=${HOME}/.aws/config,target=/root/.aws/config,relabel=private"
  CONTAINER_BUILD_OPTIONS+=(
    --format docker
  )
elif which docker > /dev/null 2>&1; then
  export CONTAINER_COMMAND="docker"
  export COMPOSE_COMMAND="docker compose"
  CONTAINER_SOCKET="/var/run/docker.sock"
  export MOUNT_SOCKET=" --mount=type=bind,source=${CONTAINER_SOCKET},target=${CONTAINER_SOCKET}"
  export MOUNT_PWD=" --mount=type=bind,source=${PWD},target=${PWD}"
  export DOCKER_BUILDKIT=1
else
  echo "No container engine found; currently only podman or docker supported."
  echo "Assuming we're in CI or development environment."
fi

export CONTAINER_AWS_OPTIONS
export CONTAINER_RUN_OPTIONS
export CONTAINER_BUILD_OPTIONS
