#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit

CONTAINER=${1:-}
source scripts/include/env-container-build "$CONTAINER"

if [ "$CONTAINER_SKIP_BUILD" == "TRUE" ]; then
  exit 0
fi

echo "+++ Building ${CONTAINER_IMAGE_REVISION} +++"
$CONTAINER_COMMAND build \
                   "${CONTAINER_BUILD_OPTIONS[@]}" \
                   --tag "${CONTAINER_IMAGE_REVISION}"
