#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit
source scripts/include/build-env

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ -n "$CI" ]; then
  if [[ "$CURRENT_BRANCH" == "main" ]]; then
    REVISION="latest"
  else
    REVISION=$GITHUB_REF_NAME
  fi
else
  REVISION=$CURRENT_BRANCH
fi

case $1 in
  base)
    CONTAINER_TARGET="base"
    CONTAINER_TAG=$BASE_GHCR_TAG
    CONTAINER_FILE="docker/Dockerfile"
    ;;

  master)
    CONTAINER_TARGET="master"
    CONTAINER_TAG=$MASTER_GHCR_TAG
    CONTAINER_FILE="docker/Dockerfile"
    ;;

  cdk-base)
    CONTAINER_TARGET="cdk-base"
    CONTAINER_TAG=$CDK_BASE_GHCR_TAG
    CONTAINER_FILE="URL"
    CONTAINER_URL="github.com/gazwald/cdk-docker.git"
    CONTAINER_BUILD_OPTIONS+=(
      --build-arg "CDK_VERSION=$CDK_VERSION"
      --build-arg "DOCKER_VERSION=$DOCKER_VERSION"
      --build-arg "NODE_VERSION=$NODE_VERSION"
    )
    ;;
  cdk)
    CONTAINER_TARGET="cdk"
    CONTAINER_TAG=$CDK_GHCR_TAG
    CONTAINER_FILE="docker/Dockerfile.dev"
    CONTAINER_BUILD_OPTIONS+=(
      --build-arg "CDK_TAG=$CDK_BASE_GHCR_TAG:cdk-base-$REVISION"
    )
    ;;

  docs)
    CONTAINER_TARGET="docs"
    CONTAINER_TAG=$DOCS_GHCR_TAG
    CONTAINER_FILE="docker/Dockerfile.dev"
    ;;

  test)
    CONTAINER_TARGET="test"
    CONTAINER_TAG=$TEST_GHCR_TAG
    CONTAINER_FILE="docker/Dockerfile.dev"
    ;;

  *)
    echo "Tag '$1' is unknown"
    exit 1
    ;;
esac

CONTAINER_TAG_LATEST="${CONTAINER_TAG}:latest"
CONTAINER_TAG_REVISION="${CONTAINER_TAG}:${CONTAINER_TARGET}-${REVISION}"
if docker inspect "$CONTAINER_TAG_LATEST" >/dev/null 2>&1; then
  CONTAINER_BUILD_OPTIONS+=(
    --cache-from "${CONTAINER_TAG_LATEST}"
  )
fi
if docker inspect "$CONTAINER_TAG_REVISION" >/dev/null 2>&1; then
  CONTAINER_BUILD_OPTIONS+=(
    --cache-from "${CONTAINER_TAG_REVISION}"
  )
fi
# if [ -n "$CI" ]; then
#   CONTAINER_BUILD_OPTIONS+=(
#     --cache-to "${CONTAINER_TAG_REVISION}"
#   )
# fi

if [[ "$CONTAINER_FILE" == "URL" ]]; then
  CONTAINER_BUILD_OPTIONS+=(
    "$CONTAINER_URL"
  )
else
  CONTAINER_BUILD_OPTIONS+=(
     --target "${CONTAINER_TARGET}"
     --file "${CONTAINER_FILE}"
     .
  )
fi



echo "+++ Building ${CONTAINER_TAG_REVISION} +++"
$CONTAINER_COMMAND build \
                   "${CONTAINER_BUILD_OPTIONS[@]}" \
                   --tag "${CONTAINER_TAG_REVISION}"

if [ -n "$CI" ]; then
  echo "+++ Pushing $CONTAINER_TAG_REVISION +++"
  $CONTAINER_COMMAND push "${CONTAINER_TAG_REVISION}"
fi
