#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit 1

source scripts/include/build-env
scripts/build-cdk > /dev/null

# shellcheck disable=SC2206
CONTAINER_RUN_OPTIONS+=(
  $MOUNT_SOCKET
  $MOUNT_PWD
)

$CONTAINER_COMMAND run \
                   "${CONTAINER_RUN_OPTIONS[@]}" \
                   "${CONTAINER_AWS_OPTIONS[@]}" \
                   "${APP_NAME}/cdk:latest" \
                   "$@"
