#!/usr/bin/env bash
set -euo pipefail

IMAGE_NAME="docker-cdk"
IMAGE_VERSION="latest"
DOCKER_SOCKET="/var/run/docker.sock"

docker run --rm \
           -it \
           --network host \
           -v ${DOCKER_SOCKET}:${DOCKER_SOCKET} \
           -v $(pwd):$(pwd) \
           -w $(pwd) \
           -e AWS_ACCESS_KEY_ID \
           -e AWS_SECRET_ACCESS_KEY \
           -e AWS_DEFAULT_REGION \
           ${IMAGE_NAME}:${IMAGE_VERSION} \
           "$@" 
