#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit 1

echo "+++ Building containers +++"
source scripts/include/build cdk >/dev/null 2>&1
echo "+++ Setting environment +++"
source scripts/include/env-container-run

if test -f cdk.out/synth.lock; then
  echo "+++ Removing synth.lock +++"
  rm cdk.out/synth.lock
fi

# shellcheck disable=SC2206
CONTAINER_RUN_OPTIONS+=(
  $MOUNT_SOCKET
  $MOUNT_PWD
  $MOUNT_AWS
)

echo "+++ Running ${CONTAINER_IMAGE_REVISION} +++"
$CONTAINER_COMMAND run \
                   "${CONTAINER_RUN_OPTIONS[@]}" \
                   "${CONTAINER_AWS_OPTIONS[@]}" \
                   "${CONTAINER_IMAGE_REVISION}" \
                   "$@"
