#!/usr/bin/env bash

cd $(dirname $0)/..

CODE="/code"
LINTER=${1:-"python"}

DOCKER_BUILDKIT=1 \
docker run -it \
           --rm \
           --mount=type=bind,source="$(pwd)"/,target=${CODE} \
           --mount=type=volume,source=apk-cache,target=/var/cache/apk \
           --mount=type=volume,source=pip-cache,target=/root/.cache/pip \
           -w ${CODE} \
           python:3-alpine \
           ${CODE}/scripts/lint_${LINTER} ${CODE}
