#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit 1

source scripts/include/build-env
scripts/build-docs > /dev/null

CONTAINER_RUN_OPTIONS+=($MOUNT_PWD)

$CONTAINER_COMMAND run \
                   ${CONTAINER_RUN_OPTIONS[@]} \
                   "${APP_NAME}/docs:latest" \
                   bash -c "${@:-bash}"
