#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

source scripts/include/build-env
scripts/build-docs > /dev/null

docker run --interactive \
           --tty \
           --rm \
           --mount=type=bind,source="$(pwd)",target="$(pwd)" \
           --workdir "$(pwd)" \
           "${APP_NAME}/docs:latest" \
           bash -c "${@:-bash}"
