#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

source scripts/include/build-env
scripts/build-test > /dev/null

docker run --interactive \
           --tty \
           --rm \
           --mount=type=bind,source="${DOCKER_SOCKET}",target="${DOCKER_SOCKET}" \
           --mount=type=bind,source="$(pwd)",target="$(pwd)" \
           --workdir "$(pwd)" \
           "${APP_NAME}/test:latest" \
           "$@"
