---
name: Deploy Docs

on:
  workflow_run:
    branches:
      - "main"
    paths:
      - '.github/workflows/deploy_docs.yaml'
      - '.github/workflows/lint_docs.yaml'
      - 'docker/Dockerfile.docs'
      - 'docs/**'
      - 'mkdocs.yaml'
      - 'poetry.lock'
      - 'pyproject.toml'

jobs:
  build:
    uses: quakeservices/master/.github/workflows/build_container.yaml@main
    with:
      target: docs
      dockerfile: Dockerfile.docs
  lint_docs:
    uses: quakeservices/master/.github/workflows/lint_docs.yaml@main
    needs: build
  lint_yaml:
    uses: quakeservices/master/.github/workflows/lint_yaml.yaml@main
    needs: build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Deploy documenation"
        run: scripts/ci/deploy_docs
