---
ignored:
  - DL3007  # Using latest is prone to errors if the image will ever update.
  - DL3008  # Pin versions in apt get install.
  - DL3009  # Delete the apt-get lists after installing something.
  - DL3013  # Pin versions in pip.
  - DL3016  # Pin versions in npm. Instead of `npm install <package>` use `npm install <package>@<version>`
  - DL3042  # Avoid use of cache directory with pip.
