# syntax=docker/dockerfile:1
FROM quakeservices/base:latest

RUN --mount=type=cache,target=/var/cache/apt \
  wget https://deb.nodesource.com/setup_current.x -O /tmp/setup_current.x && \
  bash /tmp/setup_current.x && \
  rm /tmp/setup_current.x

RUN --mount=type=cache,target=/var/cache/apt \
  apt-get install -y --no-install-recommends \
    docker \
    nodejs

RUN --mount=type=cache,target=/root/.npm \
  npm -g install aws-cdk@2.30.0
