# syntax=docker/dockerfile:1
FROM quakeservices/base:latest

RUN --mount=type=cache,target=/var/cache/apt \
  apt-get install -y docker npm

RUN --mount=type=cache,target=/root/.npm \
  npm -g install aws-cdk@latest

COPY requirements.test.txt .

RUN --mount=type=cache,target=/root/.cache/pip \
  python3 -m pip install -r requirements.test.txt
