---
version: '3.8'

# Other options for DynamoDBLocal.jar:
# -delayTransientStatuses

services:

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000/tcp"
    environment:
      REGION: 'us-west-2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://dynamodb-local:8000"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - default

  server:
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
    container_name: server
    image: ghcr.io/quakeservices/master:latest
    ports:
      - "27900:27900/udp"
      - "8080:8080/tcp"
    environment:
      DEPLOYMENT_ENVIRONMENT: 'dev'
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      REGION: 'us-west-2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:8080"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 15s
