---
site_name: Quake Services
theme: material
nav:
  - Home: index.md
  - Usage:
      - Server Administrators: usage/servers.md
      - Clients: usage/clients.md
  - Development:
      - Environment: development/environment.md
      - Contributing: development/contributing.md
  - Deployment:
      - Local: deployment/local.md
      - AWS: deployment/aws.md
  - Schema:
      - Game Protocol: schemas/game_protocol.md
      - Protocol Response: schemas/protocol_response.md
  - Reference:
      - External: references/external.md
