#!/usr/bin/env bash
set -eo pipefail

cd "$(git rev-parse --show-toplevel)"

COMMAND='prettier --write docs/'

echo "+++ Running prettier +++"
if [ -z $CI ]; then
  scripts/include/run-docs-container $COMMAND
else
  $COMMAND
fi
