---
name: Testing Master

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - '.github/workflows/testing_master.yaml'
      - 'master/**'
      - 'test/unit/master/**'
      - 'test/unit/storage/**'
      - 'pyproject.toml'
      - 'poetry.lock'
  pull_request:
    branches:
      - "main"
    paths:
      - '.github/workflows/testing_master.yaml'
      - 'master/**'
      - 'test/unit/master/**'
      - 'test/unit/storage/**'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  build:
    uses: quakeservices/master/.github/workflows/building/dev_containers.yaml@updates
  lint:
    needs: build
    uses: quakeservices/master/.github/workflows/linting/lint.yaml@updates
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Unit tests"
        run: scripts/ci/test-unit
