# syntax=docker/dockerfile:1
FROM ghcr.io/quakeservices/base:latest

WORKDIR /usr/src/app

COPY master/requirements.txt .

RUN --mount=type=cache,target=/root/.cache/pip \
  python3 -m pip install -r requirements.txt

COPY . /usr/src/app/

CMD [ "./qs.py", "--log-level", "debug", "--no-boto-logs" ]
