# syntax=docker/dockerfile:1
FROM python:3.11

RUN --mount=type=cache,target=/var/cache/apt \
  apt-get update && \
  apt-get upgrade -y

COPY pyproject.toml poetry.lock .

RUN --mount=type=cache,target=/root/.cache/pip \
  python3 -m pip install poetry
