# syntax=docker/dockerfile:1
FROM ghcr.io/quakeservices/base:latest

WORKDIR /usr/src/app

COPY . /usr/src/app/

RUN --mount=type=cache,target=/root/.cache/pip \
  poetry install --no-interaction --with 'master'

CMD [ "./qs.py", "--log-level", "debug", "--hide-boto-logs", "server", "run"]
