# syntax=docker/dockerfile:1
FROM ghcr.io/quakeservices/cdk:latest

RUN --mount=type=cache,target=/root/.npm \
  npm install --global prettier

RUN --mount=type=cache,target=/root/.cache/pip \
  poetry install --with docs
