# syntax=docker/dockerfile:1
FROM quakeservices/base:latest

WORKDIR /usr/src/app

COPY lib/masterserver/requirements.txt .

RUN --mount=type=cache,target=/root/.cache/pip \
  python3 -m pip install -r requirements.txt

COPY lib/masterserver /usr/src/app/
COPY lib/storage /usr/src/app/storage/

CMD [ "python3", "app.py" ]
