# syntax=docker.io/docker/dockerfile:1
# vim:set ft=dockerfile:

FROM python:3.12-slim

ENV PIP_ROOT_USER_ACTION=ignore

WORKDIR /tmp

COPY pyproject.toml poetry.lock .

RUN python -m pip install -U pip setuptools \
 && python -m pip install poetry==1.6.1
