# syntax=docker/dockerfile:1
FROM python:3.11

WORKDIR /tmp

COPY  pyproject.toml \
      poetry.lock \
      package.json \
      package-lock.json \
      ./

RUN --mount=type=cache,target=/root/.cache/pip \
  python3 -m pip install poetry && \
  poetry config virtualenvs.create false

RUN --mount=type=cache,target=/var/cache/apt \
  apt-get update && \
  apt-get upgrade -y
