#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit
source scripts/include/build-env

CONTAINER_RUN_OPTIONS+=($MOUNT_PWD)

echo "+++ Running Hadolint +++"
for file in $(find docker/ -type f -name 'Dockerfile*' -print | sort); do
  echo "${file}"
  $CONTAINER_COMMAND run \
                     ${CONTAINER_RUN_OPTIONS[@]} \
                     hadolint/hadolint < "${file}"
done
