#!/usr/bin/env bash
set -eo pipefail

cd "$(git rev-parse --show-toplevel)"
source scripts/include/build-env

COMMAND='
pylint
    --errors-only
    master
    deployment
    test
'

echo "+++ Running Pylint +++"
if [ -z $CI ]; then
  scripts/include/run-test-container $COMMAND
else
  $COMMAND
fi
