#!/usr/bin/env bash
set -eo pipefail

cd "$(git rev-parse --show-toplevel)" || exit 1
source scripts/include/build-env

COMMAND="pylint --errors-only master deployment test"

echo "+++ Running Pylint +++"
scripts/include/run-test-container "$COMMAND"
