#!/usr/bin/env bash
set -eo pipefail

cd "$(git rev-parse --show-toplevel)" || exit 1

COMMAND='prettier --check docs/'

echo "+++ Running prettier +++"
if [ -z "$CI" ]; then
  scripts/include/run-docs-container "$COMMAND"
else
  $COMMAND
fi
