#!/usr/bin/env bash
set -eo pipefail

cd "$(git rev-parse --show-toplevel)" || exit 1
source scripts/include/build-env

COMMAND='yamllint mkdocs.yaml .github/'

echo "+++ Running yamllint +++"
if [ -z "$CI" ]; then
  scripts/include/run-test-container "$COMMAND"
else
  $COMMAND
fi
