#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit 1

COMMAND="prettier --check docs/"

echo "+++ Running prettier +++"
scripts/include/run-docs-container "$COMMAND"
