#!/usr/bin/env bash
set -eo pipefail

cd "$(git rev-parse --show-toplevel)" || exit 1
source scripts/include/build-env

COMMAND="mypy deployment/ master/"

echo "+++ Running mypy +++"
scripts/include/run-test-container "$COMMAND"
