#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit

source scripts/include/build-env

CONTAINER_RUN_OPTIONS+=($MOUNT_PWD)

echo "+++ Running shellcheck +++"

# shellcheck disable=SC2140
$CONTAINER_COMMAND run \
                   ${CONTAINER_RUN_OPTIONS[@]} \
                   $SHELLCHECK_TAG sh -c "find /mnt/scripts -type f | xargs shellcheck"
