#!/usr/bin/env bash
set -eo pipefail

cd "$(git rev-parse --show-toplevel)" || exit 1

COMMAND=(
  yamllint
  --strict
  mkdocs.yaml
  .github/
)

echo "+++ Running yamllint +++"
scripts/include/run-test-container "${COMMAND[@]}"
