#!/usr/bin/env bash
set -eo pipefail

cd "$(git rev-parse --show-toplevel)"
source scripts/include/build-env

COMMAND='
isort
  --check-only
  lib/clients
  lib/masterserver
  lib/web-backend
  lib/storage
  deployment
'

echo "+++ Running isort +++"
if [ -z $CI ]; then
  scripts/include/run-test-container $COMMAND
else
  $COMMAND
fi
