#!/usr/bin/env bash
set -eo pipefail

cd "$(git rev-parse --show-toplevel)" || exit
source scripts/include/build-env

COMMAND="black --check ."

echo "+++ Running Black +++"
scripts/include/run-test-container "$COMMAND"
