#!/usr/bin/env bash
set -xeo pipefail

cd "$(git rev-parse --show-toplevel)" || exit

COMMAND=(
  pytest
  -vv
  --cov=master/
  test/unit/master
  test/unit/storage
)

echo "+++ Running unit tests +++"
scripts/include/run-test-container "${COMMAND[@]}"
