#!/usr/bin/env bash
set -eo pipefail

cd "$(git rev-parse --show-toplevel)"
source scripts/include/build-env

echo "+++ Running Renovate Config Validation+++"

docker run --interactive \
           --tty \
           --rm \
           --volume "$PWD/.github/renovate.json":/usr/src/app/renovate.json \
           renovate/renovate \
           renovate-config-validator
