#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit

source scripts/include/build-env
scripts/build-base

DOCKER_ARGS=""
PARENT_COMMAND=$(ps -o args= $PPID)
if [[ "$PARENT_COMMAND" =~ "scripts" ]]; then
  DOCKER_ARGS="--quiet"
fi

echo "+++ Building cdk image +++"
docker build ${DOCKER_ARGS} \
              --tag "${CDK_DOCKER_TAG}:latest" \
              --file docker/Dockerfile.cdk \
              .

docker tag "${CDK_DOCKER_TAG}:latest" "${CDK_GHCR_TAG}:latest"
