#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

source scripts/include/build-env
scripts/build-base

PARENT_COMMAND=$(ps -o args= $PPID)
if [[ "$PARENT_COMMAND" =~ "scripts" ]]; then
  DOCKER_ARGS="--quiet"
fi

echo "+++ Building test container +++"
docker build ${DOCKER_ARGS} \
              --tag ${APP_NAME}/test:latest \
              --file Dockerfile.test \
              .
