#!/usr/bin/env bash

cd "$(git rev-parse --show-toplevel)"

source scripts/include/build-env

DOCKER_ARGS=""
PARENT_COMMAND=$(ps -o args= $PPID)
if [[ "$PARENT_COMMAND" =~ "scripts" ]]; then
  DOCKER_ARGS="--quiet"
fi

echo "+++ Building base image +++"
docker build ${DOCKER_ARGS} \
              --tag ${APP_NAME}/base:latest \
              --file Dockerfile.base \
              .
