#!/usr/bin/env bash
set -euo pipefail

cd $(dirname $0)/..

APP=masterserver

echo "+++ Building ${APP} +++"
DOCKER_BUILDKIT=1 \
docker build --network host \
             -t ${APP}:latest \
             .
