#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit

source scripts/include/build-env
scripts/build-cdk

DOCKER_ARGS=""
PARENT_COMMAND=$(ps -o args= $PPID)
if [[ "$PARENT_COMMAND" =~ "scripts" ]]; then
  DOCKER_ARGS="--quiet"
fi

echo "+++ Building docs image +++"
docker build ${DOCKER_ARGS} \
              --tag "${DOCS_DOCKER_TAG}:latest" \
              --file docker/Dockerfile.docs \
              .

docker tag "${DOCS_DOCKER_TAG}:latest" "${DOCS_GHCR_TAG}:latest"
