#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

source scripts/include/build-env
scripts/build-cdk

DOCKER_ARGS=""
PARENT_COMMAND=$(ps -o args= $PPID)
if [[ "$PARENT_COMMAND" =~ "scripts" ]]; then
  DOCKER_ARGS="--quiet"
fi

echo "+++ Building docs image +++"
docker build ${DOCKER_ARGS} \
              --tag ${APP_NAME}/docs:latest \
              --file docker/Dockerfile.docs \
              .
