#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit

source scripts/include/build-env
scripts/build-base

CONTAINER_BUILD_OPTIONS=()
PARENT_COMMAND=$(ps -o args= $PPID)
if [[ "$PARENT_COMMAND" =~ "scripts" ]]; then
  CONTAINER_BUILD_OPTIONS+="--quiet"
fi

echo "+++ Building cdk image +++"
$CONTAINER_COMMAND build \
                   ${CONTAINER_BUILD_OPTIONS[@]} \
                   --tag "${CDK_DOCKER_TAG}:latest" \
                   --file docker/Dockerfile.cdk \
                   .

$CONTAINER_COMMAND tag "${CDK_DOCKER_TAG}:latest" "${CDK_GHCR_TAG}:latest"
