#!/usr/bin/env bash

cd "$(git rev-parse --show-toplevel)" || exit
source scripts/include/build-env

DOCKER_ARGS=""
PARENT_COMMAND=$(ps -o args= $PPID)
if [[ "$PARENT_COMMAND" =~ "scripts" ]]; then
  DOCKER_ARGS="--quiet"
fi

echo "+++ Building base image +++"
docker build ${DOCKER_ARGS} \
              --tag "${BASE_DOCKER_TAG}:latest" \
              --file docker/Dockerfile.base \
              .

docker tag "${BASE_DOCKER_TAG}:latest" "${BASE_GHCR_TAG}:latest"
