#!/usr/bin/env bash
set -euo pipefail

cd $(dirname $0)/..

APP=masterserver

echo "+++ Building ${APP} +++"
docker build --network host \
             -v ~/.cache/pip:/root/.cache/pip \
             -v ~/.cache/apk:/etc/apk/cache \
             -t ${APP}:latest \
             .
