#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit

source scripts/include/build-env
scripts/build-base

PARENT_COMMAND=$(ps -o args= $PPID)
if [[ "$PARENT_COMMAND" =~ "scripts" ]]; then
  CONTAINER_BUILD_OPTIONS+=("--quiet")
fi

echo "+++ Building master server +++"
$CONTAINER_COMMAND build \
                   "${CONTAINER_BUILD_OPTIONS[@]}" \
                   --tag "${MASTER_DOCKER_TAG}:latest" \
                   --file docker/Dockerfile.master \
                   .

$CONTAINER_COMMAND tag "${MASTER_DOCKER_TAG}:latest" "${MASTER_GHCR_TAG}:latest"
