#!/usr/bin/env bash
set -euo pipefail

cd $(dirname $0)/..

if ! which cdk; then
    echo "CDK command not found"
    exit 1
fi

if test -d deploy/.env; then
    cd deploy && \
      source .env/bin/activate && \
      pip install -r requirements.txt
else
    cd deploy && \
      python3 -m venv .env && \
      source .env/bin/activate && \
      pip install -r requirements.txt
fi

cdk bootstrap && cdk deploy
