#!/usr/bin/env bash

COMMAND='yamllint'

if ! $(which ${COMMAND}); then
  pip install ${COMMAND} > /dev/null
fi

echo "+++ Running YAML linter +++"
for file in $(find -type f -name '*.yml' | awk '!/docker/ && !/sample/'); do
    ${COMMAND} $file;
done
