#!/usr/bin/env sh

COMMAND='yamllint'

echo "+++ Installing yamllint dependencies +++"
if ! $(which ${COMMAND}); then
  pip install --upgrade pip
  pip install ${COMMAND}
fi

echo "+++ Running YAML linter +++"
${COMMAND} protocols/config/
