#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

source scripts/include/build-env

echo "+++ Running Pylint +++"
scripts/include/run-test-container pylint --errors-only app.py lib deployment
