#!/usr/bin/env bash
set -eo pipefail

cd "$(git rev-parse --show-toplevel)"

COMMAND='prettier --check docs/'

echo "+++ Running prettier +++"
if [ -z $CI ]; then
  scripts/include/run-test-container $COMMAND
else
  $COMMAND
fi
