#!/usr/bin/env sh

COMMAND='pylint'

echo "+++ Installing pylint dependencies +++"
if ! $(which ${COMMAND}); then
  apk add gcc musl-dev
  pip install --upgrade pip > /dev/null
  pip install -r requirements.txt > /dev/null
  pip install -r requirements.testing.txt > /dev/null
  pip install ${COMMAND} > /dev/null
fi

echo "+++ Running Python linter +++"
${COMMAND} --errors-only $(find -type f -name '*.py' | awk '!/.venv/ && !/.env/ && !/venv/')
