#!/usr/bin/env bash
set -euo pipefail

cd $(dirname $0)/..

if [test -d package ]; then rm -rf package; fi

pip install -r requirements_lambda.txt --upgrade --target package

cd package

zip -r9 ${OLDPWD}/function.zip .

cd $OLDPWD

zip -g function.zip lambda.py \
                    storage/__init__.py \
                    storage/model.py \
                    storage/cache.py

aws s3 cp function.zip s3://web-backend-lambda-package/
