#!/usr/bin/env bash
set -euo pipefail

cd $(dirname $0)/..

./scripts/lint yaml
./scripts/lint python

./scripts/test

./scripts/build

repo="ecrst-quake-v3hdrh4qq3e0"
account=${1:-$(aws sts get-caller-identity | jq '.Account' | sed 's/"//g')}
region=${2:-"us-west-2"}

$(aws ecr get-login --no-include-email --region ${region})

docker tag masterserver:latest ${account}.dkr.ecr.${region}.amazonaws.com/${repo}:latest && \
  docker push ${account}.dkr.ecr.${region}.amazonaws.com/${repo}:latest
