#!/usr/bin/env bash
set -euo pipefail

cd $(dirname $0)/..

repo="quakeservices_master"
account=${1:-$(aws sts get-caller-identity | jq '.Account' | sed 's/"//g')}
region=${2:-"ap-southeast-2"}

remote_image="${account}.dkr.ecr.${region}.amazonaws.com/${repo}:latest"

echo "+++ Logging into ECR +++"
$(aws ecr get-login --no-include-email --region ${region})
echo "+++ Remote image name ${remote_image}"
echo "+++ Tagging and pushing +++"
docker tag masterserver:latest ${remote_image}
docker push ${remote_image}
