#!/usr/bin/env bash
set -eo pipefail

cd "$(git rev-parse --show-toplevel)" || exit
source scripts/include/build-env

COMMAND="
pytest -v
  --cov=master/
  test/unit/master
  test/unit/storage
"

echo "+++ Running tests +++"
if [ -z $CI ]; then
  scripts/include/run-test-container $COMMAND
else
  $COMMAND
fi
