#!/usr/bin/env bash
set -eo pipefail

cd "$(git rev-parse --show-toplevel)" || exit
source scripts/include/build-env

COMMAND=(
  pytest
  -vv
  --cov=deployment/
  -m "cdk and unit"
)

echo "+++ Running tests +++"
if [ -z "$CI" ]; then
  scripts/include/run-test-container "${COMMAND[@]}"
else
  "${COMMAND[@]}"
fi
