#!/usr/bin/env bash
set -eo pipefail

cd "$(git rev-parse --show-toplevel)" || exit
source scripts/include/build-env

COMMAND=(
  pytest
  -vv
  --cov=master/
  --cov=deployment/
  test/unit/{master,storage}
)

echo "+++ Running unit tests +++"
if [ -z "$CI" ]; then
  scripts/include/run-test-container "${COMMAND[@]}"
else
  "${COMMAND[@]}"
fi
