#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit

source scripts/include/build-env
scripts/build-master

trap "$COMPOSE_COMMAND rm --force" EXIT

echo "+++ Running master server +++"

$COMPOSE_COMMAND up --remove-orphans
