#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit

source scripts/include/build-env
scripts/build-master

echo "+++ Running master server +++"

trap "$COMPOSE_COMMAND down" EXIT

$COMPOSE_COMMAND up --remove-orphans --force-recreate
