#!/usr/bin/env bash
set -euo pipefail

cd $(dirname $0)/..

./scripts/lint yaml
./scripts/lint python

./scripts/build

APP=masterserver

docker run -it \
           --rm \
           ${APP}:latest \
           python ./app.py
