#!/usr/bin/env sh

COMMAND='pytest'

echo "+++ Installing test dependencies +++"
if ! $(which ${COMMAND}); then
  echo "+++ Upgrade pip +++"
  pip install --upgrade pip
  pip install ${COMMAND}
  pip install -r requirements.txt
fi

echo "+++ Running unit tests +++"
${COMMAND} --cache-clear tests/unit_tests/
