#!/usr/bin/env bash

cd $(dirname $0)/..

CODE="/code"

docker run -it \
           --rm \
           -v ~/.cache/pip:/root/.cache/pip \
           -v "$(pwd)"/:${CODE} \
           -w ${CODE} \
           python:3-alpine \
           ${CODE}/scripts/tests_unit
