#!/usr/bin/env sh

COMMAND='pytest'

echo "+++ Installing test dependencies +++"
if ! $(which ${COMMAND}); then
  echo "+++ Upgrade pip +++"
  pip install --upgrade pip > /dev/null
  echo "+++ Install ${COMMAND} +++"
  pip install ${COMMAND} > /dev/null
  echo "+++ Install requirments.txt +++"
  pip install -r requirements.txt > /dev/null
fi

echo "+++ Running unit tests +++"
${COMMAND} --cache-clear tests/unit_tests/
