---
name: Build Container

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      dockerfile:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: "Hadolint"
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/${{ inputs.dockerfile }}

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Set environment"
        run: scripts/include/env-github ${{ inputs.target }}

      - name: "Buildand push"
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/${{ inputs.dockerfile }}
          platforms: linux/amd64
          build-args: |
            "CODE_DIR=${{ env.CODE_DIR }}"
            "CDK_TAG=${{ env.CDK_TAG }}"
            "CDK_VERSION=${{ env.CDK_VERSION }}"
          push: true
          tags: ${{ env.CONTAINER_IMAGE_REVISION}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
