---
# https://github.com/docker/build-push-action/blob/master/docs/advanced/push-multi-registries.md

name: Build

# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows: [Linting Docker, Linting Python, Linting YAML, Testing Master]
    types:
      - completed
    branches:
      - "main"
    paths:
      - '.github/workflows/build.yaml'
      - 'docker/**'
      - 'master/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile.base
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: |
            ghcr.io/quakeservices/base:latest

      - name: Build and push master
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile.master
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: |
            ghcr.io/quakeservices/master:latest
