---
name: Build Dev Containers

on:
  workflow_call:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Building base"
        run: ./scripts/build-base

      - name: "Building master"
        run: ./scripts/build-master

      - name: "Building cdk"
        run: ./scripts/build-cdk

      - name: "Building test"
        run: ./scripts/build-test

      - name: "Building docs"
        run: ./scripts/build-docs
