---
name: Deploy Docs

# yamllint disable-line rule:truthy
on:
  workflow_run:
    workflows: [Linting Docs, Linting YAML]
    types:
      - completed
    branches: [main]
    paths:
      - 'mkdocs.yaml'
      - 'docs/**'

concurrency:
  # yamllint disable-line rule:line-length
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
