---
name: Build Dev Containers

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Container Registry Login"
        env:
          CONTAINER_REGISTRY: ghcr.io
          CONTAINER_USERNAME: ${{ github.actor }}
          CONTAINER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: scripts/include/registry_login

      - name: "Building base"
        run: scripts/build-base

      - name: "Building cdk"
        run: scripts/build-cdk

      - name: "Building test"
        run: scripts/build-test

      - name: "Building docs"
        run: scripts/build-docs
