---
name: Lint YAML

on:
  workflow_call:

jobs:
  lint_yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Linting: yaml"
        run: scripts/ci/lint-yaml
        if: always()
