---
name: Linting

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: 'requirements.test.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.test.txt

      - name: "Linting: black"
        run: scripts/lint-black

      - name: "Linting: isort"
        run: scripts/lint-isort
        if: always()

      - name: "Linting: pylint"
        run: scripts/lint-pylint
        if: always()

      - name: "Linting: mypy"
        run: scripts/lint-mypy
        if: always()

      - name: "Linting: yaml"
        run: scripts/lint-yaml
        if: always()

      - name: "Linting: hadolint"
        run: scripts/lint-hadolint
        if: always()
