---
name: Lint Python

on:
  workflow_call:

jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Linting: black"
        run: scripts/ci/lint-black

      - name: "Linting: isort"
        run: scripts/ci/lint-isort
        if: always()

      - name: "Linting: pylint"
        run: scripts/ci/lint-pylint
        if: always()

      - name: "Linting: mypy"
        run: scripts/ci/lint-mypy
        if: always()
