---
name: Linting Docs

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - '.github/workflows/linting_docs.yaml'
      - 'mkdocs.yaml'
      - 'docs/**'
      - 'pyproject.toml'
      - 'package-lock.json'
      - 'poetry.lock'
  pull_request:
    branches:
      - "main"
    paths:
      - '.github/workflows/linting_docs.yaml'
      - 'mkdocs.yaml'
      - 'docs/**'
      - 'pyproject.toml'
      - 'package-lock.json'
      - 'poetry.lock'

concurrency:
  # yamllint disable-line rule:line-length
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install -g prettier
      - name: "Linting: Docs"
        run: ./scripts/ci/lint-docs
