---
name: Testing CDK

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - '.github/workflows/testing_cdk.yaml'
      - 'deployment/**'
      - 'test/unit/cdk/**'
      - 'pyproject.toml'
      - 'poetry.lock'
  pull_request:
    branches:
      - "main"
    paths:
      - '.github/workflows/testing_cdk.yaml'
      - 'deployment/**'
      - 'test/unit/cdk/**'
      - 'pyproject.toml'
      - 'poetry.lock'

concurrency:
  # yamllint disable-line rule:line-length
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'

jobs:
  build:
    uses: quakeservices/master/.github/workflows/build_containers.yml@updates
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: "CDK unit tests"
        run: ./scripts/ci/test-cdk
