---
name: Test CDK

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - '.github/workflows/test_cdk.yaml'
      - '.github/workflows/lint_python.yaml'
      - '.github/workflows/lint_yaml.yaml'
      - 'docker/Dockerfile.cdk'
      - 'deployment/**'
      - 'test/unit/cdk/**'
      - 'pyproject.toml'
      - 'poetry.lock'
  pull_request:
    branches:
      - "main"
    paths:
      - '.github/workflows/test_cdk.yaml'
      - '.github/workflows/lint_python.yaml'
      - '.github/workflows/lint_yaml.yaml'
      - 'docker/Dockerfile.cdk'
      - 'deployment/**'
      - 'test/unit/cdk/**'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  build:
    uses: quakeservices/master/.github/workflows/build_container.yaml@updates
    with:
      target: cdk-test
      dockerfile: Dockerfile.cdk
  lint_python:
    uses: quakeservices/master/.github/workflows/lint_python.yaml@updates
    needs: build
  lint_yaml:
    uses: quakeservices/master/.github/workflows/lint_yaml.yaml@updates
    needs: build
  test:
    needs: [lint_python, lint_yaml]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Unit Tests - CDK"
        run: scripts/ci/test-cdk
