---
name: Testing CDK

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - '.github/workflows/testing_cdk.yaml'
      - 'deployment/**'
      - 'test/unit/cdk/**'
      - 'pyproject.toml'
      - 'poetry.lock'
  pull_request:
    branches:
      - "main"
    paths:
      - '.github/workflows/testing_cdk.yaml'
      - 'deployment/**'
      - 'test/unit/cdk/**'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  build:
    uses: quakeservices/master/.github/workflows/dev_containers.yaml@updates
  lint:
    uses: quakeservices/master/.github/workflows/lint.yaml@updates
    needs: build
  test:
    needs: [build, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: "CDK unit tests"
        run: scripts/ci/test-cdk
