---
name: Master

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - '.github/workflows/test_master.yaml'
      - '.github/workflows/lint_python.yaml'
      - '.github/workflows/lint_yaml.yaml'
      - 'docker/Dockerfile'
      - 'master/**'
      - 'test/unit/master/**'
      - 'test/unit/storage/**'
      - 'pyproject.toml'
      - 'poetry.lock'
  pull_request:
    branches:
      - "main"
    paths:
      - '.github/workflows/test_master.yaml'
      - '.github/workflows/lint_python.yaml'
      - '.github/workflows/lint_yaml.yaml'
      - 'docker/Dockerfile'
      - 'master/**'
      - 'test/unit/master/**'
      - 'test/unit/storage/**'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  build:
    uses: quakeservices/master/.github/workflows/build_container.yaml@main
    with:
      target: test
      dockerfile: Dockerfile
  lint_python:
    uses: quakeservices/master/.github/workflows/lint_python.yaml@main
    needs: build
  lint_yaml:
    uses: quakeservices/master/.github/workflows/lint_yaml.yaml@main
    needs: build
  test:
    needs: [lint_python, lint_yaml]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Unit Tests - Master"
        run: scripts/ci/test-unit
