---
name: Testing CDK

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/testing_cdk.yaml'
      - 'deployment/**'
      - 'test/unit/cdk/**'
  pull_request:
    paths:
      - '.github/workflows/testing_cdk.yaml'
      - 'deployment/**'
      - 'test/unit/cdk/**'

concurrency:
  # yamllint disable-line rule:line-length
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        env:
          POETRY_VIRTUALENVS_CREATE: false
        run: |
          pipx install poetry
          poetry install --with 'cdk'
          npm install --global aws-cdk

      - name: "CDK unit tests"
        run: scripts/run-test-cdk
